version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra-seed-1:
    image: cassandra
    environment:
      CASSANDRA_LISTEN_ADDRESS: "cassandra-seed-1"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-seed-1"
    ports:
      - "7000"
      - "9042"
      - "9160"
    restart: always

  cassandra-node:
    image: cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra-seed-1"
    ports:
      - "7000"
      - "9042"
      - "9160"
    depends_on:
      - cassandra-seed-1
    restart: always

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  chatservice-seed-1:
    image: chatservice:latest
    command: "-Dakka.remote.netty.tcp.hostname=userservice-seed-1"
    depends_on:
      - cassandra-seed-1
      - kafka-1
      - kafka-2
      - kafka-3

  chatservice-node:
    image: chatservice:latest
    depends_on:
      - cassandra-seed-1
      - kafka-1
      - kafka-2
      - kafka-3
